using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyProductAttribute("pNAntContrib")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2016 Nathan Daniels.  Original Copyright (C) 2001-2012 Gerry Shaw")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("0.92.4543.0")]
[assembly: AssemblyInformationalVersionAttribute("0.92")]

